version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: user_management_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123123
      MYSQL_DATABASE: user_management
      MYSQL_USER: user_management_backend
      MYSQL_PASSWORD: 123123123
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local
